// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
  inline void cb_FreeCam_i(Fl_Button*, void*);
  static void cb_FreeCam(Fl_Button*, void*);
  inline void cb_LightControl_i(Fl_Button*, void*);
  static void cb_LightControl(Fl_Button*, void*);

  inline void cb_TilePlus_i(Fl_Button*, void*);
  static void cb_TilePlus(Fl_Button*, void*);
  inline void cb_TileMinus_i(Fl_Button*, void*);
  static void cb_TileMinus(Fl_Button*, void*);
  inline void cb_TileMirror_i(Fl_Button*, void*);
  static void cb_TileMirror(Fl_Button*, void*);

public:
  void show();
  void DBG_cb();
  void FreeCam_cb();
  void LightControl_cb();
  void TilePlus_cb();
  void TileMinus_cb();
  void TileMirror_cb();



};
#endif
